project:
  type: website

website:
  title: "tarleb"
  favicon: favicon.svg
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
    right:
      - imprint.qmd
  open-graph: true
  twitter-card:
    creator: '@kraut0xa'

format:
  html:
    theme: minty
    css: styles.css
    toc: true

filters:
  - _extensions/address.lua
  - _extensions/css-mailto-obfuscation.lua
