project:
  type: website

website:
  title: "tarleb.com"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: minty
    css: styles.css
    toc: true

filters:
  - _extensions/address.lua
